import 'movies.dart';

List<Movies> myMovies = [
    Movies(
      img: "posterFilm1.jpg",
      title: "NOAH",
      duration: "1 hr 30 min",
      category: "Action",
      rating: "A+",
      star: "Taisa Farmiga",
      globe: "IMDB",
      director: "John",
      storyLine: "The Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story The film Titanic tells the story of the love between Jack Dawson (played by Leonardo DiCaprio) and Rose DeWitt Bukater (played by Kate Winslet) that begins aboard the luxurious ship, RMS Titanic",
    ),
    Movies(
      img: "posterFilm2.jpg",
      title: "TABU",
      duration: "1 hr 25 min",
      category: "Horror",
      rating: "A",
      star: "Indah Permatasari",
      globe: "IMDB",
      director: "John",
      storyLine: "The film Titanic tells the story of the love between Jack Dawson (played by Leonardo DiCaprio) and Rose DeWitt Bukater (played by Kate Winslet) that begins aboard the luxurious ship, RMS Titanic",
    ),
    Movies(
      img: "posterFilm3.jpg",
      title: "Titanic",
      duration: "3 hr 15 min",
      category: "Drama",
      rating: "B",
      star: "Kendall Jenner",
      globe: "IMDB",
      director: "John",
      storyLine: "The film Titanic tells the story of the love between Jack Dawson (played by Leonardo DiCaprio) and Rose DeWitt Bukater (played by Kate Winslet) that begins aboard the luxurious ship, RMS Titanic",
    ),
    Movies(
      img: "posterFilm4.jpg",
      title: "Marvel",
      duration: "3 hr 15 min",
      category: "Drama",
      rating: "C",
      star: "Kendall Jenner",
      globe: "IMDB",
      director: "John",
      storyLine: "The film Titanic tells the story of the love between Jack Dawson (played by Leonardo DiCaprio) and Rose DeWitt Bukater (played by Kate Winslet) that begins aboard the luxurious ship, RMS Titanic",
    ),
  ];